# -*- coding: utf-8 -*-
"""Data Downloader

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bzr_lZGwS5dtHSmpBLZEaMpO__EcsMHk

Install dependencies
"""

!pip install datasets

"""Imports"""

from datasets import load_dataset

"""Connect to drive

Note: Before running this, add the VIP folder as a shortcut to your drive

*Borrowed this from 4644 lol*
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')

# %load_ext autoreload
# %autoreload 2

import os
#change to desired path
os.chdir("./drive/MyDrive/VIP/router/data")
# %pwd

"""List of datasets from huggingface and the required columns"""

flare_datasets = [
    "ChanceFocus/flare-fpb",
    "ChanceFocus/flare-fiqasa",
    "ChanceFocus/flare-headlines",
    "ChanceFocus/flare-finqa",
    "ChanceFocus/flare-convfinqa",
    "ChanceFocus/flare-finer-ord",
    "ChanceFocus/flare-sm-bigdata",
    "ChanceFocus/flare-sm-acl",
    "ChanceFocus/flare-sm-cikm",
    "ChanceFocus/flare-german",
    "ChanceFocus/flare-australian",
    "ChanceFocus/flare-edtsum",
    "ChanceFocus/flare-fomc",
    "ChanceFocus/flare-ner"
]

"""Function to download dataset"""

def download_dataset(dataset_name, selected_columns):
    dataset = load_dataset(dataset_name)
    dataset.save_to_disk(dataset_name)
    print(f"Dataset {dataset_name} and saved to {dataset_name}")

"""Download all datasets"""

for dataset in flare_datasets:
    download_dataset(dataset, columns)